-- Records with more than 30 retweets
SELECT  AIRLINE_SENTIMENT, 
        NEGATIVEREASON,
        AIRLINE,
        RETWEET_COUNT, 
        TWEET_LOCATION
  FROM  AIRLINE_SENTIMENT
 WHERE  RETWEET_COUNT>30;

-- check the rows count
SELECT count(*) num_rows
  FROM AIRLINE_SENTIMENT;
  
-- SYSIBM.SYSTABLES 
 SELECT  NAME, CREATOR, CTIME, COLCOUNT
   FROM  SYSIBM.SYSTABLES
  WHERE  CREATOR ='XXX'; 
  
-- SYSIBM.SYSCOLUMNS
SELECT  NAME, TBNAME, TBCREATOR, COLTYPE, NULLS, LENGTH
  FROM  SYSIBM.SYSCOLUMNS 
 WHERE  TBCREATOR='XXX'
   AND  TBNAME='AIRLINE_SENTIMENT';